# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cl < Formula
  desc "cl is a way to group all your aliases, once in a while or multiple usages
with a lot of args commands in an organized and human readable place
"
  homepage "https://github.com/rvigo/asdasdsa"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rvigo/asdasdsa/releases/download/v1.0.3/cl_1.0.3_darwin_amd64.tar.gz"
      sha256 "4f50b28345924952d4ebb18ba9a814626bb692b7742e54a7f6d7a393b07a83ce"

      def install
        bin.install "cl"
        zsh_completion.install "completions/zsh/_cl" => "_cl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rvigo/asdasdsa/releases/download/v1.0.3/cl_1.0.3_darwin_arm64.tar.gz"
      sha256 "c205d810689de5f5fb759979efb7982ce2c739cf5e05afb2128b8d1210091835"

      def install
        bin.install "cl"
        zsh_completion.install "completions/zsh/_cl" => "_cl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rvigo/asdasdsa/releases/download/v1.0.3/cl_1.0.3_linux_amd64.tar.gz"
      sha256 "a1ea06f68d4f3f87e7a599fd486ffe5ce1eac686fb88636a3be8efb643947563"

      def install
        bin.install "cl"
        zsh_completion.install "completions/zsh/_cl" => "_cl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rvigo/asdasdsa/releases/download/v1.0.3/cl_1.0.3_linux_arm64.tar.gz"
      sha256 "87e91fdfd5784567d6cb0f7177e0a55462b0cd2f8734044c700f8a5373d50cff"

      def install
        bin.install "cl"
        zsh_completion.install "completions/zsh/_cl" => "_cl"
      end
    end
  end

  def caveats
    <<~EOS
      In order to get cl completion (only available for ZSH shell),
      be sure that $(brew --prefix)/share/zsh/site-functions is present in $FPATH.
      If not, add the following line to your ~/.zshrc, BEFORE any call to compinit:
      FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
    EOS
  end
end
