# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cl < Formula
  desc "cl is a way to group all your aliases, once in a while or multiple usages
with a lot of args commands in an organized and human readable place
"
  homepage "https://github.com/rvigo/asdasdsa"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rvigo/asdasdsa/releases/download/v1.0.3/cl_1.0.3_darwin_arm64.tar.gz"
      sha256 "55a39b58dfddd38fdf16892089b0fa4024a14c2de366d0e37446f545bfec630c"

      def install
        bin.install "cl"
        zsh_completion.install "completions/zsh/_cl" => "_cl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rvigo/asdasdsa/releases/download/v1.0.3/cl_1.0.3_darwin_amd64.tar.gz"
      sha256 "29f76e8aa7cfbe12679e0d9a285b02ea182d8600386b134969e7fec0d3437a6d"

      def install
        bin.install "cl"
        zsh_completion.install "completions/zsh/_cl" => "_cl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rvigo/asdasdsa/releases/download/v1.0.3/cl_1.0.3_linux_arm64.tar.gz"
      sha256 "0036ba6ec9d65a7fae16e54f29461c4164dd0ba5d7855cc2178fd2d2b4159944"

      def install
        bin.install "cl"
        zsh_completion.install "completions/zsh/_cl" => "_cl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rvigo/asdasdsa/releases/download/v1.0.3/cl_1.0.3_linux_amd64.tar.gz"
      sha256 "1eb34f2ee40eb6b6ef43e2a145a00fb65261316ae25cb6da301600dc2fd91717"

      def install
        bin.install "cl"
        zsh_completion.install "completions/zsh/_cl" => "_cl"
      end
    end
  end

  def caveats
    <<~EOS
      In order to get cl completion (only available for ZSH shell),
      be sure that $(brew --prefix)/share/zsh/site-functions is present in $FPATH.
      If not, add the following line to your ~/.zshrc, BEFORE any call to compinit:
      FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
    EOS
  end
end
