# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cl < Formula
  desc "cl is a way to group all your aliases, once in a while or multiple usages
with a lot of args commands in an organized and human readable place
"
  homepage "https://github.com/rvigo/asdasdsa"
  version "1.0.6"
  depends_on :macos

  on_macos do
    url "https://github.com/rvigo/asdasdsa/releases/download/v1.0.6/cl_1.0.6_darwin_amd64.tar.gz"
    sha256 "cdd78ff6de853182ed6f923dbbf9e259ae971a5fddb86688452b1f3e8e83f3c5"

    def install
      bin.install "cl"
      zsh_completion.install "completions/zsh/_cl" => "_cl"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Cl
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  def caveats
    <<~EOS
      In order to get cl completion (only available for ZSH shell),
      be sure that $(brew --prefix)/share/zsh/site-functions is present in $FPATH.
      If not, add the following line to your ~/.zshrc, BEFORE any call to compinit:
      FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
    EOS
  end
end
