name: release-automated
on:
  push:
    tag: 
      - 'v[0-9]+.[0-9]+.[0-9]+-beta'
      - 'v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'
      - '!v[0-9].[0-9].[0-9]'

jobs:
  check:
    name: Check tag
    runs-on: ubuntu-latest
    steps: 
      - name: check
        run: |
          echo "Checking tag"
          echo "Tag: ${{ github.ref }}"