name: release-automated
on:
  push:
    tag: 
      - 'v*.*.*-beta'
      - 'v*.*.*-alpha'
      - '!v[0-9].[0-9].[0-9]'

jobs:
  check:
    name: Check tag
    runs-on: ubuntu-latest
    steps: 
      - name: check
        run: |
          echo "Checking tag"
          echo "Tag: ${{ github.ref }}"